@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.mrd.server.controllers.AuthController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_108383 { 
   	label=mrd
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_384502606 { 
   	label=server
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AuthController1235953704[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AuthController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authenticationService: AuthenticationService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tokenRepository: VerificationTokenRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userRepository: UserRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ signIn(signInRequest: SignInRequest): ResponseEntity&lt;JwtAuthenticationResponse&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ signUp(signUpRequest: SignUpRequest): ResponseEntity&lt;User&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyAccount(token: String): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ verifyEmail(email: String): ResponseEntity&lt;Boolean&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AuthenticationServiceImpl460554943[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AuthenticationServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authenticationManager: AuthenticationManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   emailService: EmailService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   jwtService: JwtService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   passwordEncoder: PasswordEncoder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   trainerRepository: TrainerRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userRepository: UserRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   verificationTokenRepository: VerificationTokenRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ signIn(signInRequest: SignInRequest): JwtAuthenticationResponse</TD></TR>
<TR><TD ALIGN="LEFT" >+ signUp(signUpRequest: SignUpRequest): User</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EmailServiceImpl460554943[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EmailServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mailSender: JavaMailSender [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ sendEmail(to: List&lt;String&gt;, subject: String, text: String, attachment: File)</TD></TR>
<TR><TD ALIGN="LEFT" >+ sendVerificationEmail(user: User, token: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JwtServiceImpl460554943[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JwtServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   expirationTime: long [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- extractAllClaims(token: String): Claims</TD></TR>
<TR><TD ALIGN="LEFT" >- extractClaim(token: String, claimsResolver: Function&lt;Claims, T&gt;): T</TD></TR>
<TR><TD ALIGN="LEFT" >+ extractUserName(token: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ generateToken(userDetails: UserDetails): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ isTokenExpired(token: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ isTokenValid(token: String, userDetails: UserDetails): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AuthController1235953704 -> AuthenticationServiceImpl460554943[arrowhead=none];
AuthenticationServiceImpl460554943 -> EmailServiceImpl460554943[arrowhead=none];
AuthenticationServiceImpl460554943 -> JwtServiceImpl460554943[arrowhead=none];
    
}
@enduml